version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_BACKEND_URL=https://api.parkon.app
      - REACT_APP_APP_NAME=Park On
      - REACT_APP_DOMAIN=parkon.app
    volumes:
      - ./ssl:/etc/ssl/certs
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=parkon_production_db
      - CORS_ORIGINS=https://parkon.app,https://www.parkon.app
      - TFL_API_KEY=79bb56428ea54847885426e03ed7c9ee
      - APP_DOMAIN=parkon.app
      - API_DOMAIN=api.parkon.app
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backup:/backup
    environment:
      - MONGO_INITDB_DATABASE=parkon_production_db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  mongodb_data: